### ISSUE TITLE
Add in a message handler that responds to cache/uncache/status commands

### ISSUE THREAD

**Issue by jeffposnick** [wibblymat/shed#2]
Since `caches` isn't currently exposed in `window` for use in controlled pages, the only way for a controlled page to cache/uncache or query for the cached status of a resource is to `postMessage()` to the service worker, which would then perform the action and return a response.

It would be nice if `shed` registered a `message` event handler that listened for a standard set of "commands" and performed those actions, returning a standard response to the controlled page. The specifics of the request/response message format are open for debate, but just standardizing on something simple should be sufficient.

(I'm happy to contribute this code, but I wanted to file this for tracking/discussion.)

**Comment by wibblymat** [comment]
I've been back and forth on this in my mind since you first posted it. Right now I'm thinking punt until requested by the community.

A postMessage handler is pretty easy to write, and with Shed the developer is already writing the SW themselves. I don't want to second guess them by implementing a handler that will clash with what they are doing themselves.

**Comment by jeffposnick** [comment]
Sure thing. `window.caches` will be a thing eventually, anyway.
