### ISSUE TITLE
Use of setTimeout to detect onfetch overwrites

### ISSUE THREAD

**Issue by jakearchibald** [wibblymat/shed#9]
I like the idea, but would this work better?

```js
Object.defineProperty(self, 'onfetch', { set: function() {
  throw Error("Oi! No! Use addEventLister!")
}});
// etc
```

**Comment by wibblymat** [comment]
My mind is blown. I was testing this, and had a test case like:

```javascript
self.addEventListener('install', function() { console.log('first'); });
self.oninstall = function() { console.log('second'); };
self.addEventListener('install', function() { console.log('third'); });
```

The console output was
```
first
second
third
```

So it turns out that this kind of check isn't even needed at all, at least in Chrome. I always assumed that the `onfoo = ...` way overwrote previously add listeners.

Serves me right for making assumptions, I guess.
